# antes de instalar valide se a rede externa ja existe:
# docker network create kairix_network

services:
  postgres:
    image: postgres:18
    container_name: kairix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kairix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kairix2025}
      POSTGRES_DB: ${POSTGRES_DB:-kairix_financeiro}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5414:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-kairix} -d ${POSTGRES_DB:-kairix_financeiro}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kairix_network

volumes:
  postgres_data:

networks:
  kairix_network:
    name: kairix_network
    external: true
